import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bold technical test | Harold Pineda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">    
      <body className={cn('relative h-full font-sans antialiased', montserrat.className)}>
        <main className="className='relative flex flex-col min-h-screen">
          <Navbar />

            {children}
        </main>
      </body>
    </html>
  );
}
